on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
    
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Docker images
        uses: actions/cache@v2
        with:
          path: |
            /root/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose*.yml') }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Server Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mortensonasy/tdp-server:latest
          file: ./backend/cmd/Dockerfile

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /root/tdp
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
